<?xml version='1.0'?>
<xsl:stylesheet version="1.1" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
xmlns:fo="http://www.w3.org/1999/XSL/Format"  exclude-result-prefixes="fo">	

<xsl:template name="header-footer" >

		 <fo:static-content flow-name="xsl-region-before">
					<fo:table width="500pt" table-layout="fixed" border-bottom-style="solid" border-bottom-color="lightgray" border-bottom-width="1pt"  >
						<fo:table-body> <fo:table-row>
								<fo:table-cell>
									<fo:block font-size="10pt" text-align="left" font-style="italic"> 
										<xsl:value-of select="@Title" />
									</fo:block>
								</fo:table-cell>
								<fo:table-cell width="20pt">
										<fo:block font-size="10pt" text-align="right"  font-style="italic" ><fo:page-number padding-before="20pt"/></fo:block>  
								</fo:table-cell>
						</fo:table-row></fo:table-body>
					</fo:table>
					
		</fo:static-content>
				
		<fo:static-content flow-name="xsl-region-after">
				
					<fo:table width="500pt" table-layout="fixed" border-top-style="solid" border-top-color="lightgray" border-top-width="1pt" padding-top="5pt">
							<fo:table-body>	<fo:table-row>
									<fo:table-cell >
										<fo:block font-size="10pt" text-align="left"> 
											
											 <xsl:value-of select="name()" /> generated by Astrosoft from http://innovativeastrosolutions.com 
											 
										</fo:block>
									</fo:table-cell>
									<fo:table-cell width="20pt">
										<fo:block font-size="10pt" text-align="right"  font-style="italic" ><fo:page-number padding-before="20pt"/></fo:block>
									</fo:table-cell>
							</fo:table-row></fo:table-body>
						</fo:table>
					
					
		</fo:static-content>

	</xsl:template>
</xsl:stylesheet>
