<?xml version='1.0'?>
<xsl:stylesheet version="1.1" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
xmlns:fo="http://www.w3.org/1999/XSL/Format"  exclude-result-prefixes="fo">	

<xsl:template name="panchang-header-footer" >

		 <fo:static-content flow-name="xsl-region-before">
					<fo:table width="785pt" table-layout="fixed"   >
						<fo:table-body> <fo:table-row>
								<fo:table-cell width="350pt">
									<fo:block font-size="10pt" text-align="left" font-style="italic"> 
										<xsl:value-of select="//Panchang/@Location" />
										
									</fo:block>
								</fo:table-cell>
								<fo:table-cell>
									<fo:block font-size="10pt" text-align="left" font-style="italic"> 
										<xsl:value-of select="@Title" />
									</fo:block>
								</fo:table-cell>
								<fo:table-cell width="20pt">
										<fo:block font-size="10pt" text-align="right"  font-style="italic" ><fo:page-number padding-before="20pt"/></fo:block>  
								</fo:table-cell>
						</fo:table-row></fo:table-body>
					</fo:table>
					
		</fo:static-content>
				
		<fo:static-content flow-name="xsl-region-after">
				
					<fo:table width="785pt" table-layout="fixed" padding-top="5pt">
							<fo:table-body>	<fo:table-row>
									<fo:table-cell >
										<fo:block font-size="10pt" text-align="left"> 
											
											 Panchang generated by A. Elango, Astrologer, 72/2, Nehru Street, Moolappalayam, Erode, TN.
											 
										</fo:block>
									</fo:table-cell>
									<fo:table-cell width="20pt">
										<fo:block font-size="10pt" text-align="right"  font-style="italic" ><fo:page-number padding-before="20pt"/></fo:block>
									</fo:table-cell>
							</fo:table-row></fo:table-body>
						</fo:table>
					
					
		</fo:static-content>

	</xsl:template>
</xsl:stylesheet>
